import { RouterState } from "connected-next-router";
import { WalletState } from "./wallet";
import { AccountsState } from "./account";
import { LocalUserAccountsState } from "./localAccount";
import { PostState } from "./post";
import { LixiesState } from "./lixi";
import { ClaimsState } from "./claim";
import { EnvelopesState } from "./envelope";
import { LoadingState } from "./loading";
import { ModalState } from "./modal";
import { ActionSheetState } from "./action-sheet";
import { ToastState } from "./toast";
import { ErrorState } from "./error";
import { SettingsState } from "./settings";
import { NotificationsState } from "./notification";
import { PageState } from "./page";
import { TokenState } from "./token";
import { CountriesState, StatesState } from "./country";
import { PageCategory } from "@bcpros/lixi-models";
import { EntityState } from "@reduxjs/toolkit";
import { BurnState } from "./burn";
import { PageMessageSessionState } from "./message";
import { CombinedState } from "@reduxjs/toolkit/query";
import { ActionState } from "./action";
import { PersistState } from "redux-persist";

export type LixiStoreStateInterface = {
  router: RouterState;
  wallet: WalletState;
  accounts: AccountsState;
  localAccounts: LocalUserAccountsState;
  posts: PostState;
  lixies: LixiesState;
  claims: ClaimsState;
  envelopes: EnvelopesState;
  loading: LoadingState;
  modal: ModalState;
  actionSheet: ActionSheetState;
  toast: ToastState;
  error: ErrorState;
  settings: SettingsState;
  notifications: NotificationsState;
  pages: PageState;
  tokens: TokenState;
  countries: CountriesState;
  states: StatesState;
  categories: EntityState<PageCategory, number> & {
    selectedCategoryId: number;
  };
  burn: BurnState;
  pageMessage: PageMessageSessionState;
  api: CombinedState<{}, never, "api">;
  _persist: PersistState;
  action: ActionState;
}