  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { api } from 'src/api/baseApi';
export type PinFieldsFragment = {
  __typename?: 'Pin';
  id: string;
  pinableId?: string | null;
  page?: {
    __typename?: 'Page';
    id: string;
    avatar?: string | null;
    name: string;
    createPostFee: string;
    createCommentFee: string;
    pageAccount: { __typename?: 'Account'; id: number; name: string; address: string };
  } | null;
  account?: { __typename?: 'Account'; id: number; name: string; address: string } | null;
};

export type PinQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type PinQuery = {
  __typename?: 'Query';
  pin: {
    __typename?: 'Pin';
    id: string;
    pinableId?: string | null;
    page?: {
      __typename?: 'Page';
      id: string;
      avatar?: string | null;
      name: string;
      createPostFee: string;
      createCommentFee: string;
      pageAccount: { __typename?: 'Account'; id: number; name: string; address: string };
    } | null;
    account?: { __typename?: 'Account'; id: number; name: string; address: string } | null;
  };
};

export type CreatePostPinMutationVariables = Types.Exact<{
  input: Types.CreatePostPinInput;
}>;

export type CreatePostPinMutation = {
  __typename?: 'Mutation';
  createPostPin: {
    __typename?: 'Pin';
    id: string;
    pinableId?: string | null;
    page?: {
      __typename?: 'Page';
      id: string;
      avatar?: string | null;
      name: string;
      createPostFee: string;
      createCommentFee: string;
      pageAccount: { __typename?: 'Account'; id: number; name: string; address: string };
    } | null;
    account?: { __typename?: 'Account'; id: number; name: string; address: string } | null;
  };
};

export type RemovePostPinMutationVariables = Types.Exact<{
  input: Types.RemovePostPinInput;
}>;

export type RemovePostPinMutation = {
  __typename?: 'Mutation';
  removePostPin: {
    __typename?: 'Pin';
    id: string;
    pinableId?: string | null;
    page?: {
      __typename?: 'Page';
      id: string;
      avatar?: string | null;
      name: string;
      createPostFee: string;
      createCommentFee: string;
      pageAccount: { __typename?: 'Account'; id: number; name: string; address: string };
    } | null;
    account?: { __typename?: 'Account'; id: number; name: string; address: string } | null;
  };
};

export const PinFieldsFragmentDoc = `
    fragment PinFields on Pin {
  id
  pinableId
  page {
    id
    avatar
    name
    createPostFee
    createCommentFee
    pageAccount {
      id
      name
      address
    }
  }
  account {
    id
    name
    address
  }
}
    `;
export const PinDocument = `
    query Pin($id: String!) {
  pin(id: $id) {
    ...PinFields
  }
}
    ${PinFieldsFragmentDoc}`;
export const CreatePostPinDocument = `
    mutation CreatePostPin($input: CreatePostPinInput!) {
  createPostPin(data: $input) {
    ...PinFields
  }
}
    ${PinFieldsFragmentDoc}`;
export const RemovePostPinDocument = `
    mutation RemovePostPin($input: RemovePostPinInput!) {
  removePostPin(data: $input) {
    ...PinFields
  }
}
    ${PinFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    Pin: build.query<PinQuery, PinQueryVariables>({
      query: variables => ({ document: PinDocument, variables })
    }),
    CreatePostPin: build.mutation<CreatePostPinMutation, CreatePostPinMutationVariables>({
      query: variables => ({ document: CreatePostPinDocument, variables })
    }),
    RemovePostPin: build.mutation<RemovePostPinMutation, RemovePostPinMutationVariables>({
      query: variables => ({ document: RemovePostPinDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const { usePinQuery, useLazyPinQuery, useCreatePostPinMutation, useRemovePostPinMutation } = injectedRtkApi;
