import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: '../app-lixi-api/schema.graphql',
  generates: {
    'src/generated/types.generated.ts': {
      plugins: ['typescript'],
    },
    'src': {
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'generated/types.generated.ts',
      },
      plugins: [
        {
          add: {
            content: `
              /* eslint-disable */
              /**
               *
               * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
               *
               * instead, edit one of the .graphql files in this project and run
               *
               * pnpm graphql-codegen
               *
               * for this file to be re-created
               */
            `,
          },
        },
        'typescript-operations',
        {
          'typescript-rtk-query': {
            importBaseApiFrom: 'src/api/baseApi',
            exportHooks: false,
            overrideExisting: true,
          },
        },
      ],
    }
  },
};
export default config;