/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { api } from '@store/baseApi';
export type DisputeFieldsFragment = {
  __typename?: 'Dispute';
  id: string;
  reason?: string | null;
  createdBy: string;
  status: Types.DisputeStatus;
  createdAt: any;
  updatedAt: any;
  escrowOrder: {
    __typename?: 'EscrowOrder';
    id: string;
    status: Types.EscrowOrderStatus;
    createdAt: any;
    updatedAt: any;
  };
};

export type DisputeQueryVariables = Types.Exact<{
  id: Types.Scalars['String']['input'];
}>;

export type DisputeQuery = {
  __typename?: 'Query';
  dispute: {
    __typename?: 'Dispute';
    id: string;
    reason?: string | null;
    createdBy: string;
    status: Types.DisputeStatus;
    createdAt: any;
    updatedAt: any;
    escrowOrder: {
      __typename?: 'EscrowOrder';
      id: string;
      status: Types.EscrowOrderStatus;
      createdAt: any;
      updatedAt: any;
    };
  };
};

export type CreateDisputeMutationVariables = Types.Exact<{
  input: Types.CreateDisputeInput;
}>;

export type CreateDisputeMutation = { __typename?: 'Mutation'; createDispute: { __typename?: 'Dispute'; id: string } };

export type UpdateDisputeMutationVariables = Types.Exact<{
  input: Types.UpdateDisputeInput;
}>;

export type UpdateDisputeMutation = { __typename?: 'Mutation'; updateDispute: { __typename?: 'Dispute'; id: string } };

export const DisputeFieldsFragmentDoc = `
    fragment DisputeFields on Dispute {
  id
  escrowOrder {
    id
    status
    createdAt
    updatedAt
  }
  reason
  createdBy
  status
  createdAt
  updatedAt
}
    `;
export const DisputeDocument = `
    query Dispute($id: String!) {
  dispute(id: $id) {
    ...DisputeFields
  }
}
    ${DisputeFieldsFragmentDoc}`;
export const CreateDisputeDocument = `
    mutation CreateDispute($input: CreateDisputeInput!) {
  createDispute(data: $input) {
    id
  }
}
    `;
export const UpdateDisputeDocument = `
    mutation UpdateDispute($input: UpdateDisputeInput!) {
  updateDispute(data: $input) {
    id
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    Dispute: build.query<DisputeQuery, DisputeQueryVariables>({
      query: variables => ({ document: DisputeDocument, variables })
    }),
    CreateDispute: build.mutation<CreateDisputeMutation, CreateDisputeMutationVariables>({
      query: variables => ({ document: CreateDisputeDocument, variables })
    }),
    UpdateDispute: build.mutation<UpdateDisputeMutation, UpdateDisputeMutationVariables>({
      query: variables => ({ document: UpdateDisputeDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
