/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { api } from '@store/baseApi';
export type EscrowOrderFieldsFragment = {
  __typename?: 'EscrowOrder';
  id: string;
  message?: string | null;
  escrowScript: string;
  nonce: string;
  escrowTxid?: string | null;
  releaseTxid?: string | null;
  cancelTxid?: string | null;
  price: number;
  amount: number;
  status: Types.EscrowOrderStatus;
  createdAt: any;
  updatedAt: any;
  arbitratorAccount: {
    __typename?: 'Account';
    id: number;
    publicKey?: string | null;
    hash160?: string | null;
    telegramId?: string | null;
  };
  buyerAccount: {
    __typename?: 'Account';
    id: number;
    publicKey?: string | null;
    hash160?: string | null;
    telegramId?: string | null;
  };
  sellerAccount: {
    __typename?: 'Account';
    id: number;
    publicKey?: string | null;
    hash160?: string | null;
    telegramId?: string | null;
  };
  moderatorAccount: {
    __typename?: 'Account';
    id: number;
    publicKey?: string | null;
    hash160?: string | null;
    telegramId?: string | null;
  };
  paymentMethod: { __typename?: 'PaymentMethod'; id: number; name: string };
  offer: { __typename?: 'Offer'; postId: string; message: string };
};

export type EscrowOrderQueryVariables = Types.Exact<{
  id: Types.Scalars['String']['input'];
}>;

export type EscrowOrderQuery = {
  __typename?: 'Query';
  escrowOrder: {
    __typename?: 'EscrowOrder';
    id: string;
    message?: string | null;
    escrowScript: string;
    nonce: string;
    escrowTxid?: string | null;
    releaseTxid?: string | null;
    cancelTxid?: string | null;
    price: number;
    amount: number;
    status: Types.EscrowOrderStatus;
    createdAt: any;
    updatedAt: any;
    arbitratorAccount: {
      __typename?: 'Account';
      id: number;
      publicKey?: string | null;
      hash160?: string | null;
      telegramId?: string | null;
    };
    buyerAccount: {
      __typename?: 'Account';
      id: number;
      publicKey?: string | null;
      hash160?: string | null;
      telegramId?: string | null;
    };
    sellerAccount: {
      __typename?: 'Account';
      id: number;
      publicKey?: string | null;
      hash160?: string | null;
      telegramId?: string | null;
    };
    moderatorAccount: {
      __typename?: 'Account';
      id: number;
      publicKey?: string | null;
      hash160?: string | null;
      telegramId?: string | null;
    };
    paymentMethod: { __typename?: 'PaymentMethod'; id: number; name: string };
    offer: { __typename?: 'Offer'; postId: string; message: string };
  };
};

export type CreateEscrowOrderMutationVariables = Types.Exact<{
  input: Types.CreateEscrowOrderInput;
}>;

export type CreateEscrowOrderMutation = {
  __typename?: 'Mutation';
  createEscrowOrder: { __typename?: 'EscrowOrder'; id: string };
};

export type UpdateEscrowOrderStatusMutationVariables = Types.Exact<{
  orderId: Types.Scalars['String']['input'];
  status: Types.EscrowOrderStatus;
  txid?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;

export type UpdateEscrowOrderStatusMutation = {
  __typename?: 'Mutation';
  updateEscrowOrderStatus: {
    __typename?: 'EscrowOrder';
    id: string;
    message?: string | null;
    price: number;
    amount: number;
    status: Types.EscrowOrderStatus;
    createdAt: any;
    updatedAt: any;
  };
};

export const EscrowOrderFieldsFragmentDoc = `
    fragment EscrowOrderFields on EscrowOrder {
  id
  message
  arbitratorAccount {
    id
    publicKey
    hash160
    telegramId
  }
  buyerAccount {
    id
    publicKey
    hash160
    telegramId
  }
  sellerAccount {
    id
    publicKey
    hash160
    telegramId
  }
  moderatorAccount {
    id
    publicKey
    hash160
    telegramId
  }
  paymentMethod {
    id
    name
  }
  offer {
    postId
    message
  }
  escrowScript
  nonce
  escrowTxid
  releaseTxid
  cancelTxid
  price
  amount
  status
  createdAt
  updatedAt
}
    `;
export const EscrowOrderDocument = `
    query EscrowOrder($id: String!) {
  escrowOrder(id: $id) {
    ...EscrowOrderFields
  }
}
    ${EscrowOrderFieldsFragmentDoc}`;
export const CreateEscrowOrderDocument = `
    mutation CreateEscrowOrder($input: CreateEscrowOrderInput!) {
  createEscrowOrder(data: $input) {
    id
  }
}
    `;
export const UpdateEscrowOrderStatusDocument = `
    mutation UpdateEscrowOrderStatus($orderId: String!, $status: EscrowOrderStatus!, $txid: String) {
  updateEscrowOrderStatus(orderId: $orderId, status: $status, txid: $txid) {
    id
    message
    price
    amount
    status
    createdAt
    updatedAt
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    EscrowOrder: build.query<EscrowOrderQuery, EscrowOrderQueryVariables>({
      query: variables => ({ document: EscrowOrderDocument, variables })
    }),
    CreateEscrowOrder: build.mutation<CreateEscrowOrderMutation, CreateEscrowOrderMutationVariables>({
      query: variables => ({ document: CreateEscrowOrderDocument, variables })
    }),
    UpdateEscrowOrderStatus: build.mutation<UpdateEscrowOrderStatusMutation, UpdateEscrowOrderStatusMutationVariables>({
      query: variables => ({ document: UpdateEscrowOrderStatusDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
