/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { BasicPageInfoFieldsFragmentDoc } from '../../graphql/fragments/basic-page-info-fields.fragment.generated';
import { api } from '@store/baseApi';
export type OfferFieldsFragment = {
  __typename?: 'Offer';
  id: string;
  publicKey: string;
  message: string;
  price: string;
  orderLimitMin: number;
  orderLimitMax: number;
  paymentMethods: Array<{
    __typename?: 'OfferPaymentMethod';
    paymentMethod: { __typename?: 'PaymentMethod'; name: string };
  }>;
};

export type CreateOfferMutationVariables = Types.Exact<{
  input: Types.CreateOfferInput;
}>;

export type CreateOfferMutation = {
  __typename?: 'Mutation';
  createOffer: {
    __typename?: 'Offer';
    id: string;
    publicKey: string;
    message: string;
    price: string;
    orderLimitMin: number;
    orderLimitMax: number;
    paymentMethods: Array<{
      __typename?: 'OfferPaymentMethod';
      paymentMethod: { __typename?: 'PaymentMethod'; name: string };
    }>;
  };
};

export type AllOfferQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']['input']>;
  before?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  last?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;

export type AllOfferQuery = {
  __typename?: 'Query';
  allOffer: {
    __typename?: 'OfferBasicConnection';
    totalCount: number;
    edges: Array<{
      __typename?: 'OfferBasicEdge';
      cursor: string;
      node: {
        __typename?: 'Offer';
        id: string;
        publicKey: string;
        message: string;
        price: string;
        orderLimitMin: number;
        orderLimitMax: number;
        paymentMethods: Array<{
          __typename?: 'OfferPaymentMethod';
          paymentMethod: { __typename?: 'PaymentMethod'; name: string };
        }>;
      };
    }>;
    pageInfo: { __typename?: 'BasicPageInfo'; endCursor: string; hasNextPage: boolean };
  };
};

export const OfferFieldsFragmentDoc = `
    fragment OfferFields on Offer {
  id
  publicKey
  message
  price
  orderLimitMin
  orderLimitMax
  paymentMethods {
    paymentMethod {
      name
    }
  }
}
    `;
export const CreateOfferDocument = `
    mutation CreateOffer($input: CreateOfferInput!) {
  createOffer(data: $input) {
    ...OfferFields
  }
}
    ${OfferFieldsFragmentDoc}`;
export const AllOfferDocument = `
    query AllOffer($after: String, $before: String, $first: Int, $last: Int) {
  allOffer(after: $after, before: $before, first: $first, last: $last) {
    totalCount
    edges {
      cursor
      node {
        ...OfferFields
      }
    }
    pageInfo {
      ...BasicPageInfoFields
    }
  }
}
    ${OfferFieldsFragmentDoc}
${BasicPageInfoFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    CreateOffer: build.mutation<CreateOfferMutation, CreateOfferMutationVariables>({
      query: variables => ({ document: CreateOfferDocument, variables })
    }),
    AllOffer: build.query<AllOfferQuery, AllOfferQueryVariables | void>({
      query: variables => ({ document: AllOfferDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
