  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import {
  PageInfoFieldsFragmentDoc,
  PostMeiliPageInfoFieldsFragmentDoc
} from '../../graphql/fragments/page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type MessageSessionFieldsFragment = {
  __typename?: 'MessageSession';
  id: string;
  lixiAmount?: number | null;
  sessionOpen?: boolean | null;
  createdAt?: any | null;
  updatedAt?: any | null;
  lixi?: { __typename?: 'LixiModel'; id: string } | null;
};

export type MessageSessionQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type MessageSessionQuery = {
  __typename?: 'Query';
  messageSession: {
    __typename?: 'MessageSession';
    id: string;
    lixiAmount?: number | null;
    sessionOpen?: boolean | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    lixi?: { __typename?: 'LixiModel'; id: string } | null;
  };
};

export type MessageSessionByPageMessageSessionIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  id?: Types.InputMaybe<Types.Scalars['String']>;
  orderBy?: Types.InputMaybe<Types.MessageSessionOrder>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type MessageSessionByPageMessageSessionIdQuery = {
  __typename?: 'Query';
  allMessageSessionByPageMessageSessionId: {
    __typename?: 'MessageSessionConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'MessageSessionEdge';
      cursor: string;
      node: {
        __typename?: 'MessageSession';
        id: string;
        lixiAmount?: number | null;
        sessionOpen?: boolean | null;
        createdAt?: any | null;
        updatedAt?: any | null;
        lixi?: { __typename?: 'LixiModel'; id: string } | null;
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type CreateMessageSessionMutationVariables = Types.Exact<{
  input: Types.CreateMessageSessionInput;
}>;

export type CreateMessageSessionMutation = {
  __typename?: 'Mutation';
  createMessageSession: {
    __typename?: 'MessageSession';
    id: string;
    lixiAmount?: number | null;
    sessionOpen?: boolean | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    lixi?: { __typename?: 'LixiModel'; id: string } | null;
  };
};

export const MessageSessionFieldsFragmentDoc = `
    fragment MessageSessionFields on MessageSession {
  id
  lixi {
    id
  }
  lixiAmount
  sessionOpen
  createdAt
  updatedAt
}
    `;
export const MessageSessionDocument = `
    query MessageSession($id: String!) {
  messageSession(id: $id) {
    ...MessageSessionFields
  }
}
    ${MessageSessionFieldsFragmentDoc}`;
export const MessageSessionByPageMessageSessionIdDocument = `
    query MessageSessionByPageMessageSessionId($after: String, $before: String, $first: Int = 20, $last: Int, $id: String, $orderBy: MessageSessionOrder, $skip: Int) {
  allMessageSessionByPageMessageSessionId(
    after: $after
    before: $before
    first: $first
    last: $last
    id: $id
    orderBy: $orderBy
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...MessageSessionFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${MessageSessionFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const CreateMessageSessionDocument = `
    mutation CreateMessageSession($input: CreateMessageSessionInput!) {
  createMessageSession(data: $input) {
    ...MessageSessionFields
  }
}
    ${MessageSessionFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  endpoints: build => ({
    MessageSession: build.query<MessageSessionQuery, MessageSessionQueryVariables>({
      query: variables => ({ document: MessageSessionDocument, variables })
    }),
    MessageSessionByPageMessageSessionId: build.query<
      MessageSessionByPageMessageSessionIdQuery,
      MessageSessionByPageMessageSessionIdQueryVariables | void
    >({
      query: variables => ({ document: MessageSessionByPageMessageSessionIdDocument, variables })
    }),
    CreateMessageSession: build.mutation<CreateMessageSessionMutation, CreateMessageSessionMutationVariables>({
      query: variables => ({ document: CreateMessageSessionDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const {
  useMessageSessionQuery,
  useLazyMessageSessionQuery,
  useMessageSessionByPageMessageSessionIdQuery,
  useLazyMessageSessionByPageMessageSessionIdQuery,
  useCreateMessageSessionMutation
} = injectedRtkApi;
