  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import {
  PageInfoFieldsFragmentDoc,
  PostMeiliPageInfoFieldsFragmentDoc
} from '../../graphql/fragments/page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type PageMessageSessionFieldsFragment = {
  __typename?: 'PageMessageSession';
  id: string;
  createdAt?: any | null;
  updatedAt?: any | null;
  page?: { __typename?: 'Page'; id: string; name: string } | null;
  account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
  messageSessions?: Array<{
    __typename?: 'MessageSession';
    id: string;
    lixiAmount?: number | null;
    sessionOpen?: boolean | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    lixi?: { __typename?: 'LixiModel'; id: string } | null;
  }> | null;
};

export type PageMessageSessionQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type PageMessageSessionQuery = {
  __typename?: 'Query';
  pageMessageSession: {
    __typename?: 'PageMessageSession';
    id: string;
    createdAt?: any | null;
    updatedAt?: any | null;
    page?: { __typename?: 'Page'; id: string; name: string } | null;
    account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
    messageSessions?: Array<{
      __typename?: 'MessageSession';
      id: string;
      lixiAmount?: number | null;
      sessionOpen?: boolean | null;
      createdAt?: any | null;
      updatedAt?: any | null;
      lixi?: { __typename?: 'LixiModel'; id: string } | null;
    }> | null;
  };
};

export type PageMessageSessionByPageIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  id?: Types.InputMaybe<Types.Scalars['String']>;
  orderBy?: Types.InputMaybe<Types.PageMessageSessionOrder>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type PageMessageSessionByPageIdQuery = {
  __typename?: 'Query';
  allPageMessageSessionByPageId: {
    __typename?: 'PageMessageSessionConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'PageMessageSessionEdge';
      cursor: string;
      node: {
        __typename?: 'PageMessageSession';
        id: string;
        createdAt?: any | null;
        updatedAt?: any | null;
        page?: { __typename?: 'Page'; id: string; name: string } | null;
        account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
        messageSessions?: Array<{
          __typename?: 'MessageSession';
          id: string;
          lixiAmount?: number | null;
          sessionOpen?: boolean | null;
          createdAt?: any | null;
          updatedAt?: any | null;
          lixi?: { __typename?: 'LixiModel'; id: string } | null;
        }> | null;
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type PageMessageSessionByAccountIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  id?: Types.InputMaybe<Types.Scalars['Int']>;
  orderBy?: Types.InputMaybe<Types.PageMessageSessionOrder>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type PageMessageSessionByAccountIdQuery = {
  __typename?: 'Query';
  allPageMessageSessionByAccountId: {
    __typename?: 'PageMessageSessionConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'PageMessageSessionEdge';
      cursor: string;
      node: {
        __typename?: 'PageMessageSession';
        id: string;
        createdAt?: any | null;
        updatedAt?: any | null;
        page?: { __typename?: 'Page'; id: string; name: string } | null;
        account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
        messageSessions?: Array<{
          __typename?: 'MessageSession';
          id: string;
          lixiAmount?: number | null;
          sessionOpen?: boolean | null;
          createdAt?: any | null;
          updatedAt?: any | null;
          lixi?: { __typename?: 'LixiModel'; id: string } | null;
        }> | null;
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type UserHadMessageToPageQueryVariables = Types.Exact<{
  accountId?: Types.InputMaybe<Types.Scalars['Int']>;
  pageId?: Types.InputMaybe<Types.Scalars['String']>;
}>;

export type UserHadMessageToPageQuery = {
  __typename?: 'Query';
  userHadMessageToPage: {
    __typename?: 'PageMessageSession';
    id: string;
    createdAt?: any | null;
    updatedAt?: any | null;
    page?: { __typename?: 'Page'; id: string; name: string } | null;
    account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
    messageSessions?: Array<{
      __typename?: 'MessageSession';
      id: string;
      lixiAmount?: number | null;
      sessionOpen?: boolean | null;
      createdAt?: any | null;
      updatedAt?: any | null;
      lixi?: { __typename?: 'LixiModel'; id: string } | null;
    }> | null;
  };
};

export type CreatePageMessageSessionMutationVariables = Types.Exact<{
  input: Types.CreatePageMessageInput;
}>;

export type CreatePageMessageSessionMutation = {
  __typename?: 'Mutation';
  createPageMessageSession: {
    __typename?: 'PageMessageSession';
    id: string;
    createdAt?: any | null;
    updatedAt?: any | null;
    page?: { __typename?: 'Page'; id: string; name: string } | null;
    account?: { __typename?: 'Account'; id: string; name: string; address: string } | null;
    messageSessions?: Array<{
      __typename?: 'MessageSession';
      id: string;
      lixiAmount?: number | null;
      sessionOpen?: boolean | null;
      createdAt?: any | null;
      updatedAt?: any | null;
      lixi?: { __typename?: 'LixiModel'; id: string } | null;
    }> | null;
  };
};

export const PageMessageSessionFieldsFragmentDoc = `
    fragment PageMessageSessionFields on PageMessageSession {
  id
  page {
    id
    name
  }
  account {
    id
    name
    address
  }
  messageSessions {
    id
    lixi {
      id
    }
    lixiAmount
    sessionOpen
    createdAt
    updatedAt
  }
  createdAt
  updatedAt
}
    `;
export const PageMessageSessionDocument = `
    query PageMessageSession($id: String!) {
  pageMessageSession(id: $id) {
    ...PageMessageSessionFields
  }
}
    ${PageMessageSessionFieldsFragmentDoc}`;
export const PageMessageSessionByPageIdDocument = `
    query PageMessageSessionByPageId($after: String, $before: String, $first: Int = 20, $last: Int, $id: String, $orderBy: PageMessageSessionOrder, $skip: Int) {
  allPageMessageSessionByPageId(
    after: $after
    before: $before
    first: $first
    last: $last
    id: $id
    orderBy: $orderBy
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...PageMessageSessionFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${PageMessageSessionFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const PageMessageSessionByAccountIdDocument = `
    query PageMessageSessionByAccountId($after: String, $before: String, $first: Int = 20, $last: Int, $id: Int, $orderBy: PageMessageSessionOrder, $skip: Int) {
  allPageMessageSessionByAccountId(
    after: $after
    before: $before
    first: $first
    last: $last
    id: $id
    orderBy: $orderBy
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...PageMessageSessionFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${PageMessageSessionFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const UserHadMessageToPageDocument = `
    query UserHadMessageToPage($accountId: Int, $pageId: String) {
  userHadMessageToPage(accountId: $accountId, pageId: $pageId) {
    ...PageMessageSessionFields
  }
}
    ${PageMessageSessionFieldsFragmentDoc}`;
export const CreatePageMessageSessionDocument = `
    mutation CreatePageMessageSession($input: CreatePageMessageInput!) {
  createPageMessageSession(data: $input) {
    ...PageMessageSessionFields
  }
}
    ${PageMessageSessionFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  endpoints: build => ({
    PageMessageSession: build.query<PageMessageSessionQuery, PageMessageSessionQueryVariables>({
      query: variables => ({ document: PageMessageSessionDocument, variables })
    }),
    PageMessageSessionByPageId: build.query<
      PageMessageSessionByPageIdQuery,
      PageMessageSessionByPageIdQueryVariables | void
    >({
      query: variables => ({ document: PageMessageSessionByPageIdDocument, variables })
    }),
    PageMessageSessionByAccountId: build.query<
      PageMessageSessionByAccountIdQuery,
      PageMessageSessionByAccountIdQueryVariables | void
    >({
      query: variables => ({ document: PageMessageSessionByAccountIdDocument, variables })
    }),
    UserHadMessageToPage: build.query<UserHadMessageToPageQuery, UserHadMessageToPageQueryVariables | void>({
      query: variables => ({ document: UserHadMessageToPageDocument, variables })
    }),
    CreatePageMessageSession: build.mutation<
      CreatePageMessageSessionMutation,
      CreatePageMessageSessionMutationVariables
    >({
      query: variables => ({ document: CreatePageMessageSessionDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const {
  usePageMessageSessionQuery,
  useLazyPageMessageSessionQuery,
  usePageMessageSessionByPageIdQuery,
  useLazyPageMessageSessionByPageIdQuery,
  usePageMessageSessionByAccountIdQuery,
  useLazyPageMessageSessionByAccountIdQuery,
  useUserHadMessageToPageQuery,
  useLazyUserHadMessageToPageQuery,
  useCreatePageMessageSessionMutation
} = injectedRtkApi;
