  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import {
  PageInfoFieldsFragmentDoc,
  PostMeiliPageInfoFieldsFragmentDoc
} from '../../graphql/fragments/page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type CommentQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type CommentQuery = {
  __typename?: 'Query';
  comment: {
    __typename?: 'Comment';
    id: string;
    commentText: string;
    commentByPublicKey?: string | null;
    commentableId?: string | null;
    danaBurnUp: number;
    danaBurnDown: number;
    danaBurnScore: number;
    createdAt: any;
    updatedAt: any;
    commentAccount: { __typename?: 'Account'; address: string; id: number; name: string; avatar?: string | null };
    commentDana?: {
      __typename?: 'CommentDana';
      danaBurnUp: number;
      danaBurnDown: number;
      danaBurnScore: number;
      version: number;
    } | null;
    commentable?: { __typename?: 'Commentable'; id: string; type: Types.CommentType; commentToId: string } | null;
  };
};

export type CommentsToCommentableIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  orderBy?: Types.InputMaybe<Types.CommentOrder>;
  id?: Types.InputMaybe<Types.Scalars['String']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type CommentsToCommentableIdQuery = {
  __typename?: 'Query';
  commentsToCommentableId: {
    __typename?: 'CommentConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'CommentEdge';
      cursor: string;
      node: {
        __typename?: 'Comment';
        id: string;
        commentText: string;
        commentByPublicKey?: string | null;
        commentableId?: string | null;
        danaBurnUp: number;
        danaBurnDown: number;
        danaBurnScore: number;
        createdAt: any;
        updatedAt: any;
        commentAccount: { __typename?: 'Account'; address: string; id: number; name: string; avatar?: string | null };
        commentDana?: {
          __typename?: 'CommentDana';
          danaBurnUp: number;
          danaBurnDown: number;
          danaBurnScore: number;
          version: number;
        } | null;
        commentable?: { __typename?: 'Commentable'; id: string; type: Types.CommentType; commentToId: string } | null;
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type CommentFieldsFragment = {
  __typename?: 'Comment';
  id: string;
  commentText: string;
  commentByPublicKey?: string | null;
  commentableId?: string | null;
  danaBurnUp: number;
  danaBurnDown: number;
  danaBurnScore: number;
  createdAt: any;
  updatedAt: any;
  commentAccount: { __typename?: 'Account'; address: string; id: number; name: string; avatar?: string | null };
  commentDana?: {
    __typename?: 'CommentDana';
    danaBurnUp: number;
    danaBurnDown: number;
    danaBurnScore: number;
    version: number;
  } | null;
  commentable?: { __typename?: 'Commentable'; id: string; type: Types.CommentType; commentToId: string } | null;
};

export type CreateCommentMutationVariables = Types.Exact<{
  input: Types.CreateCommentInput;
}>;

export type CreateCommentMutation = {
  __typename?: 'Mutation';
  createComment: {
    __typename?: 'Comment';
    id: string;
    commentText: string;
    commentByPublicKey?: string | null;
    commentableId?: string | null;
    danaBurnUp: number;
    danaBurnDown: number;
    danaBurnScore: number;
    createdAt: any;
    updatedAt: any;
    commentAccount: { __typename?: 'Account'; address: string; id: number; name: string; avatar?: string | null };
    commentDana?: {
      __typename?: 'CommentDana';
      danaBurnUp: number;
      danaBurnDown: number;
      danaBurnScore: number;
      version: number;
    } | null;
    commentable?: { __typename?: 'Commentable'; id: string; type: Types.CommentType; commentToId: string } | null;
  };
};

export const CommentFieldsFragmentDoc = `
    fragment CommentFields on Comment {
  id
  commentText
  commentAccount {
    address
    id
    name
    avatar
  }
  commentByPublicKey
  commentableId
  danaBurnUp
  danaBurnDown
  danaBurnScore
  commentDana {
    danaBurnUp
    danaBurnDown
    danaBurnScore
    version
  }
  createdAt
  updatedAt
  commentable {
    id
    type
    commentToId
  }
}
    `;
export const CommentDocument = `
    query Comment($id: String!) {
  comment(id: $id) {
    ...CommentFields
  }
}
    ${CommentFieldsFragmentDoc}`;
export const CommentsToCommentableIdDocument = `
    query CommentsToCommentableId($after: String, $before: String, $first: Int = 20, $last: Int, $orderBy: CommentOrder, $id: String, $skip: Int) {
  commentsToCommentableId(
    after: $after
    before: $before
    first: $first
    last: $last
    orderBy: $orderBy
    id: $id
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...CommentFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${CommentFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const CreateCommentDocument = `
    mutation createComment($input: CreateCommentInput!) {
  createComment(data: $input) {
    ...CommentFields
  }
}
    ${CommentFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    Comment: build.query<CommentQuery, CommentQueryVariables>({
      query: variables => ({ document: CommentDocument, variables })
    }),
    CommentsToCommentableId: build.query<CommentsToCommentableIdQuery, CommentsToCommentableIdQueryVariables | void>({
      query: variables => ({ document: CommentsToCommentableIdDocument, variables })
    }),
    createComment: build.mutation<CreateCommentMutation, CreateCommentMutationVariables>({
      query: variables => ({ document: CreateCommentDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const {
  useCommentQuery,
  useLazyCommentQuery,
  useCommentsToCommentableIdQuery,
  useLazyCommentsToCommentableIdQuery,
  useCreateCommentMutation
} = injectedRtkApi;
