export const LIST_CURRENCIES_USED = [
  { code: 'AED', name: 'United Arab Emirates Dirham', fixAmount: 100, country: 'AE' },
  { code: 'AFN', name: 'Afghan Afghani', fixAmount: 10000, country: 'AF' },
  { code: 'ALL', name: 'Albanian Lek', fixAmount: 1000000, country: 'AL' },
  { code: 'AMD', name: 'Armenian Dram', fixAmount: 1000, country: 'AM' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', fixAmount: 10, country: 'NL' },
  { code: 'AOA', name: 'Angolan Kwanza', fixAmount: 100, country: 'AO' },
  { code: 'ARS', name: 'Argentine Peso', fixAmount: 1000000, country: 'AR' },
  { code: 'AUD', name: 'Australian Dollar', fixAmount: 10000, country: 'AU' },
  { code: 'AWG', name: 'Aruban Florin', fixAmount: 1000, country: 'AW' },
  { code: 'AZN', name: 'Azerbaijani Manat', fixAmount: 100, country: 'AZ' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', fixAmount: 1000000, country: 'BA' },
  { code: 'BBD', name: 'Barbadian Dollar', fixAmount: 1000, country: 'BB' },
  { code: 'BDT', name: 'Bangladeshi Taka', fixAmount: 1000000, country: 'BD' },
  { code: 'BGN', name: 'Bulgarian Lev', fixAmount: 1000, country: 'BG' },
  { code: 'BHD', name: 'Bahraini Dinar', fixAmount: 1000000, country: 'BH' },
  { code: 'BIF', name: 'Burundian Franc', fixAmount: 10, country: 'BI' },
  { code: 'BMD', name: 'Bermudian Dollar', fixAmount: 10000, country: 'BM' },
  { code: 'BND', name: 'Brunei Dollar', fixAmount: 100, country: 'BN' },
  { code: 'BOB', name: 'Bolivian Boliviano', fixAmount: 100, country: 'BO' },
  { code: 'BRL', name: 'Brazilian Real', fixAmount: 1000000, country: 'BR' },
  { code: 'BSD', name: 'Bahamian Dollar', fixAmount: 10000, country: 'BS' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', fixAmount: 100, country: 'BT' },
  { code: 'BWP', name: 'Botswana Pula', fixAmount: 1000, country: 'BW' },
  { code: 'BYN', name: 'Belarusian Ruble', fixAmount: 1000000, country: 'BY' },
  { code: 'BYR', name: 'Belarusian Ruble (Old)', fixAmount: 10000, country: 'BY' },
  { code: 'BZD', name: 'Belize Dollar', fixAmount: 1000, country: 'BZ' },
  { code: 'CAD', name: 'Canadian Dollar', fixAmount: 100, country: 'CA' },
  { code: 'CDF', name: 'Congolese Franc', fixAmount: 1000000, country: 'CD' },
  { code: 'CHF', name: 'Swiss Franc', fixAmount: 100, country: 'CH' },
  { code: 'CLF', name: 'Chilean Unit of Account (UF)', fixAmount: 10000, country: 'CL' },
  { code: 'CLP', name: 'Chilean Peso', fixAmount: 1000000, country: 'CL' },
  { code: 'CNY', name: 'Chinese Yuan', fixAmount: 1000, country: 'CN' },
  { code: 'COP', name: 'Colombian Peso', fixAmount: 10000, country: 'CO' },
  { code: 'CRC', name: 'Costa Rican Colón', fixAmount: 1000000, country: 'CR' },
  { code: 'CUC', name: 'Cuban Convertible Peso', fixAmount: 1000000, country: 'CU' },
  { code: 'CUP', name: 'Cuban Peso', fixAmount: 10000, country: 'CU' },
  { code: 'CVE', name: 'Cape Verdean Escudo', fixAmount: 100, country: 'CV' },
  { code: 'CZK', name: 'Czech Koruna', fixAmount: 1000, country: 'CZ' },
  { code: 'DJF', name: 'Djiboutian Franc', fixAmount: 1000000, country: 'DJ' },
  { code: 'DKK', name: 'Danish Krone', fixAmount: 10000, country: 'DK' },
  { code: 'DOP', name: 'Dominican Peso', fixAmount: 1000, country: 'DO' },
  { code: 'DZD', name: 'Algerian Dinar', fixAmount: 1000000, country: 'DZ' },
  { code: 'EGP', name: 'Egyptian Pound', fixAmount: 1000, country: 'EG' },
  { code: 'ERN', name: 'Eritrean Nakfa', fixAmount: 1000000, country: 'ER' },
  { code: 'ETB', name: 'Ethiopian Birr', fixAmount: 1000000, country: 'ET' },
  { code: 'EUR', name: 'Euro', fixAmount: 1000, country: 'EU' },
  { code: 'FJD', name: 'Fijian Dollar', fixAmount: 100, country: 'FJ' },
  { code: 'FKP', name: 'Falkland Islands Pound', fixAmount: 10000, country: 'FK' },
  { code: 'GBP', name: 'British Pound Sterling', fixAmount: 1000, country: 'GB' },
  { code: 'GEL', name: 'Georgian Lari', fixAmount: 10000, country: 'GE' },
  { code: 'GGP', name: 'Guernsey Pound', fixAmount: 1000, country: 'GG' },
  { code: 'GHS', name: 'Ghanaian Cedi', fixAmount: 1000000, country: 'GH' },
  { code: 'GIP', name: 'Gibraltar Pound', fixAmount: 1000000, country: 'GI' },
  { code: 'GMD', name: 'Gambian Dalasi', fixAmount: 1000, country: 'GM' },
  { code: 'GNF', name: 'Guinean Franc', fixAmount: 1000000, country: 'GN' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', fixAmount: 10000, country: 'GT' },
  { code: 'GYD', name: 'Guyanaese Dollar', fixAmount: 100, country: 'GY' },
  { code: 'HKD', name: 'Hong Kong Dollar', fixAmount: 1000, country: 'HK' },
  { code: 'HNL', name: 'Honduran Lempira', fixAmount: 1000000, country: 'HN' },
  { code: 'HRK', name: 'Croatian Kuna', fixAmount: 100, country: 'HR' },
  { code: 'HTG', name: 'Haitian Gourde', fixAmount: 1000000, country: 'HT' },
  { code: 'HUF', name: 'Hungarian Forint', fixAmount: 10000, country: 'HU' },
  { code: 'IDR', name: 'Indonesian Rupiah', fixAmount: 1000000, country: 'ID' },
  { code: 'ILS', name: 'Israeli New Shekel', fixAmount: 1000000, country: 'IL' },
  { code: 'IMP', name: 'Isle of Man Pound', fixAmount: 100, country: 'IM' },
  { code: 'INR', name: 'Indian Rupee', fixAmount: 100, country: 'IN' },
  { code: 'IQD', name: 'Iraqi Dinar', fixAmount: 1000, country: 'IQ' },
  { code: 'IRR', name: 'Iranian Rial', fixAmount: 1000000, country: 'IR' },
  { code: 'ISK', name: 'Icelandic Króna', fixAmount: 1000000, country: 'IS' },
  { code: 'JEP', name: 'Jersey Pound', fixAmount: 1000, country: 'JE' },
  { code: 'JMD', name: 'Jamaican Dollar', fixAmount: 1000000, country: 'JM' },
  { code: 'JOD', name: 'Jordanian Dinar', fixAmount: 1000, country: 'JO' },
  { code: 'JPY', name: 'Japanese Yen', fixAmount: 100, country: 'JP' },
  { code: 'KES', name: 'Kenyan Shilling', fixAmount: 1000, country: 'KE' },
  { code: 'KGS', name: 'Kyrgyzstani Som', fixAmount: 1000000, country: 'KG' },
  { code: 'KHR', name: 'Cambodian Riel', fixAmount: 100, country: 'KH' },
  { code: 'KMF', name: 'Comorian Franc', fixAmount: 1000, country: 'KM' },
  { code: 'KPW', name: 'North Korean Won', fixAmount: 1000, country: 'KP' },
  { code: 'KRW', name: 'South Korean Won', fixAmount: 1000, country: 'KR' },
  { code: 'KWD', name: 'Kuwaiti Dinar', fixAmount: 1000, country: 'KW' },
  { code: 'KYD', name: 'Cayman Islands Dollar', fixAmount: 100, country: 'KY' },
  { code: 'KZT', name: 'Kazakhstani Tenge', fixAmount: 10000, country: 'KZ' },
  { code: 'LAK', name: 'Lao Kip', fixAmount: 1000000, country: 'LA' },
  { code: 'LBP', name: 'Lebanese Pound', fixAmount: 1000, country: 'LB' },
  { code: 'LKR', name: 'Sri Lankan Rupee', fixAmount: 10000, country: 'LK' },
  { code: 'LRD', name: 'Liberian Dollar', fixAmount: 1000, country: 'LR' },
  { code: 'LSL', name: 'Lesotho Loti', fixAmount: 1000, country: 'LS' },
  { code: 'LTL', name: 'Lithuanian Litas', fixAmount: 1000, country: 'LT' },
  { code: 'LVL', name: 'Latvian Lats', fixAmount: 100, country: 'LV' },
  { code: 'LYD', name: 'Libyan Dinar', fixAmount: 1000, country: 'LY' },
  { code: 'MAD', name: 'Moroccan Dirham', fixAmount: 1000, country: 'MA' },
  { code: 'MDL', name: 'Moldovan Leu', fixAmount: 1000, country: 'MD' },
  { code: 'MGA', name: 'Malagasy Ariary', fixAmount: 1000000, country: 'MG' },
  { code: 'MKD', name: 'Macedonian Denar', fixAmount: 1000, country: 'MK' },
  { code: 'MMK', name: 'Myanmar Kyat', fixAmount: 1000000, country: 'MM' },
  { code: 'MNT', name: 'Mongolian Tugrik', fixAmount: 1000000, country: 'MN' },
  { code: 'MOP', name: 'Macanese Pataca', fixAmount: 1000, country: 'MO' },
  { code: 'MRO', name: 'Mauritanian Ouguiya (pre-2018)', fixAmount: 1000, country: 'MR' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', fixAmount: 1000, country: 'MR' },
  { code: 'MUR', name: 'Mauritian Rupee', fixAmount: 1000, country: 'MU' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', fixAmount: 1000, country: 'MV' },
  { code: 'MWK', name: 'Malawian Kwacha', fixAmount: 1000000, country: 'MW' },
  { code: 'MXN', name: 'Mexican Peso', fixAmount: 1000, country: 'MX' },
  { code: 'MYR', name: 'Malaysian Ringgit', fixAmount: 1000, country: 'MY' },
  { code: 'MZN', name: 'Mozambican Metical', fixAmount: 1000000, country: 'MZ' },
  { code: 'NAD', name: 'Namibian Dollar', fixAmount: 1000, country: 'NA' },
  { code: 'NGN', name: 'Nigerian Naira', fixAmount: 1000, country: 'NG' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', fixAmount: 1000, country: 'NI' },
  { code: 'NOK', name: 'Norwegian Krone', fixAmount: 1000, country: 'NO' },
  { code: 'NPR', name: 'Nepalese Rupee', fixAmount: 1000, country: 'NP' },
  { code: 'NZD', name: 'New Zealand Dollar', fixAmount: 1000, country: 'NZ' },
  { code: 'OMR', name: 'Omani Rial', fixAmount: 1000, country: 'OM' },
  { code: 'PAB', name: 'Panamanian Balboa', fixAmount: 100, country: 'PA' },
  { code: 'PEN', name: 'Peruvian Sol', fixAmount: 1000, country: 'PE' },
  { code: 'PGK', name: 'Papua New Guinean Kina', fixAmount: 100, country: 'PG' },
  { code: 'PHP', name: 'Philippine Peso', fixAmount: 1000, country: 'PH' },
  { code: 'PKR', name: 'Pakistani Rupee', fixAmount: 1000, country: 'PK' },
  { code: 'PLN', name: 'Polish Złoty', fixAmount: 1000, country: 'PL' },
  { code: 'PYG', name: 'Paraguayan Guarani', fixAmount: 1000000, country: 'PY' },
  { code: 'QAR', name: 'Qatari Riyal', fixAmount: 1000, country: 'QA' },
  { code: 'RON', name: 'Romanian Leu', fixAmount: 1000, country: 'RO' },
  { code: 'RSD', name: 'Serbian Dinar', fixAmount: 1000, country: 'RS' },
  { code: 'RUB', name: 'Russian Ruble', fixAmount: 1000, country: 'RU' },
  { code: 'RWF', name: 'Rwandan Franc', fixAmount: 1000000, country: 'RW' },
  { code: 'SAR', name: 'Saudi Riyal', fixAmount: 1000, country: 'SA' },
  { code: 'SBD', name: 'Solomon Islands Dollar', fixAmount: 100, country: 'SB' },
  { code: 'SCR', name: 'Seychellois Rupee', fixAmount: 1000, country: 'SC' },
  { code: 'SDG', name: 'Sudanese Pound', fixAmount: 1000000, country: 'SD' },
  { code: 'SEK', name: 'Swedish Krona', fixAmount: 1000, country: 'SE' },
  { code: 'SGD', name: 'Singapore Dollar', fixAmount: 1000, country: 'SG' },
  { code: 'SHP', name: 'Saint Helena Pound', fixAmount: 10000, country: 'SH' },
  { code: 'SLE', name: 'Sierra Leonean Leone', fixAmount: 1000, country: 'SL' },
  { code: 'SLL', name: 'Sierra Leone Leone', fixAmount: 1000000, country: 'SL' },
  { code: 'SOS', name: 'Somali Shilling', fixAmount: 100, country: 'SO' },
  { code: 'SRD', name: 'Surinamese Dollar', fixAmount: 1000, country: 'SR' },
  { code: 'STD', name: 'São Tomé and Príncipe Dobra', fixAmount: 1000000, country: 'ST' },
  { code: 'STN', name: 'São Tomé and Príncipe New Dobra', fixAmount: 10000, country: 'ST' },
  { code: 'SVC', name: 'Salvadoran Colón', fixAmount: 100, country: 'SV' },
  { code: 'SYP', name: 'Syrian Pound', fixAmount: 1000000, country: 'SY' },
  { code: 'SZL', name: 'Swazi Lilangeni', fixAmount: 10000, country: 'SZ' },
  { code: 'THB', name: 'Thai Baht', fixAmount: 1000, country: 'TH' },
  { code: 'TJS', name: 'Tajikistani Somoni', fixAmount: 100, country: 'TJ' },
  { code: 'TMT', name: 'Turkmenistani Manat', fixAmount: 10000, country: 'TM' },
  { code: 'TND', name: 'Tunisian Dinar', fixAmount: 100, country: 'TN' },
  { code: 'TOP', name: 'Tongan Paʻanga', fixAmount: 1000000, country: 'TO' },
  { code: 'TRY', name: 'Turkish Lira', fixAmount: 1000, country: 'TR' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', fixAmount: 100, country: 'TT' },
  { code: 'TWD', name: 'New Taiwan Dollar', fixAmount: 1000000, country: 'TW' },
  { code: 'TZS', name: 'Tanzanian Shilling', fixAmount: 10000, country: 'TZ' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', fixAmount: 100, country: 'UA' },
  { code: 'UGX', name: 'Ugandan Shilling', fixAmount: 1000000, country: 'UG' },
  { code: 'USD', name: 'United States Dollar', fixAmount: 1000, country: 'US' },
  { code: 'UYU', name: 'Uruguayan Peso', fixAmount: 1000000, country: 'UY' },
  { code: 'UZS', name: 'Uzbekistani Som', fixAmount: 10000, country: 'UZ' },
  { code: 'VEF', name: 'Venezuelan Bolívar', fixAmount: 1000000, country: 'VE' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', fixAmount: 100, country: 'VE' },
  { code: 'VND', name: 'Vietnam Dong', fixAmount: 1000000, country: 'VN' },
  { code: 'VUV', name: 'Vanuatu Vatu', fixAmount: 1000000, country: 'VU' },
  { code: 'WST', name: 'Samoan Tala', fixAmount: 100, country: 'WS' },
  { code: 'XAF', name: 'CFA Franc (Central Africa)', fixAmount: 1000, country: 'XAF' },
  { code: 'XAG', name: 'Silver Ounce', fixAmount: 10000, country: 'XAG' },
  { code: 'XAU', name: 'Gold Ounce', fixAmount: 1000, country: 'XAU' },
  { code: 'XCD', name: 'East Caribbean Dollar', fixAmount: 100, country: 'XCD' },
  { code: 'XDR', name: 'Special Drawing Rights', fixAmount: 1000000, country: 'XDR' },
  { code: 'XOF', name: 'CFA Franc (West Africa)', fixAmount: 1000, country: 'XOF' },
  { code: 'XPD', name: 'Palladium Ounce', fixAmount: 100, country: 'XPD' },
  { code: 'XPF', name: 'CFP Franc', fixAmount: 1000, country: 'XPF' },
  { code: 'XPT', name: 'Platinum Ounce', fixAmount: 10000, country: 'XPT' },
  { code: 'YER', name: 'Yemeni Rial', fixAmount: 1000, country: 'YE' },
  { code: 'ZAR', name: 'South African Rand', fixAmount: 10000, country: 'ZA' },
  { code: 'ZMK', name: 'Zambian Kwacha', fixAmount: 1000000, country: 'ZM' },
  { code: 'ZMW', name: 'Zambian Kwacha', fixAmount: 100, country: 'ZM' },
  { code: 'ZWG', name: 'Zimbabwe Gold Bond', fixAmount: 10000, country: 'ZW' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', fixAmount: 1000, country: 'ZW' }
];
