export const LIST_CURRENCIES_USED = [
  { code: 'USD', name: 'US Dollar', fixAmount: 10, country: 'US' },
  { code: 'AUD', name: 'Australian Dollar', fixAmount: 10, country: 'AU' },
  { code: 'VND', name: 'Vietnam Dong', fixAmount: 1000000, country: 'VN' },
  { code: 'HNL', name: 'Honduran Lempira', fixAmount: 100, country: 'HN' },
  { code: 'INR', name: 'Indian Rupee', fixAmount: 1000, country: 'IN' },
  { code: 'BRL', name: 'Brazilian Real', fixAmount: 100, country: 'BR' },
  { code: 'CAD', name: 'Canadian Dollar', fixAmount: 10, country: 'CA' },
  { code: 'CHF', name: 'Swiss Franc', fixAmount: 10, country: 'CH' },
  { code: 'EUR', name: 'Euro', fixAmount: 10, country: 'EU' },
  { code: 'GBP', name: 'Great British Pound', fixAmount: 10, country: 'GB' },
  { code: 'HKD', name: 'Honk Kong Dollar', fixAmount: 100, country: 'HK' },
  { code: 'JPY', name: 'Japanese Yen', fixAmount: 1000, country: 'JP' },
  { code: 'KRW', name: 'South Korean Won', fixAmount: 10000, country: 'KR' },
  { code: 'MXN', name: 'Mexican Peso', fixAmount: 100, country: 'MX' },
  { code: 'NOK', name: 'Norwegian Krone', fixAmount: 100, country: 'NO' },
  { code: 'NZD', name: 'New Zealand Dollar', fixAmount: 10, country: 'NZ' },
  { code: 'PHP', name: 'Philippine Peso', fixAmount: 1000, country: 'PH' },
  { code: 'RUB', name: 'Russian Ruble', fixAmount: 1000, country: 'RU' },
  { code: 'SEK', name: 'Swedish Krona', fixAmount: 100, country: 'SE' },
  { code: 'SGD', name: 'Singapore Dollar', fixAmount: 10, country: 'SG' },
  { code: 'THB', name: 'Thai Baht', fixAmount: 100, country: 'TH' },
  { code: 'VEF', name: 'Venezuelan Bolívar', fixAmount: 1000000, country: 'VE' },
  { code: 'XCD', name: 'Eastern Caribbean Dollar', fixAmount: 10, country: 'AG' }, // Antigua and Barbuda as an example
  { code: 'ZAR', name: 'South African Rand', fixAmount: 100, country: 'ZA' },
  { code: 'CNY', name: 'Chinese Yuan', fixAmount: 100, country: 'CN' }
];
