  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import {
  PageInfoFieldsFragmentDoc,
  PostMeiliPageInfoFieldsFragmentDoc
} from '../../graphql/fragments/page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type BookmarkFieldsFragment = {
  __typename?: 'Bookmark';
  id: string;
  bookmarkId: string;
  type?: Types.BookmarkType | null;
  createdAt?: any | null;
  updatedAt?: any | null;
  account: { __typename?: 'Account'; address: string; id: number; name: string };
};

export type BookmarkQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type BookmarkQuery = {
  __typename?: 'Query';
  bookmark: {
    __typename?: 'Bookmark';
    id: string;
    bookmarkId: string;
    type?: Types.BookmarkType | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    account: { __typename?: 'Account'; address: string; id: number; name: string };
  };
};

export type BookmarkByAccountIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  accountId: Types.Scalars['Int'];
  bookmarkType: Types.BookmarkType;
  orderBy?: Types.InputMaybe<Types.BookmarkOrder>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type BookmarkByAccountIdQuery = {
  __typename?: 'Query';
  allBookmarkByAccountId: {
    __typename?: 'BookmarkConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'BookmarkEdge';
      cursor: string;
      node: {
        __typename?: 'Bookmark';
        id: string;
        bookmarkId: string;
        type?: Types.BookmarkType | null;
        createdAt?: any | null;
        updatedAt?: any | null;
        account: { __typename?: 'Account'; address: string; id: number; name: string };
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type CheckIfHasBookmarkedQueryVariables = Types.Exact<{
  bookmarkId: Types.Scalars['String'];
  bookmarkType: Types.BookmarkType;
}>;

export type CheckIfHasBookmarkedQuery = { __typename?: 'Query'; checkIfHasBookmarked: boolean };

export type CreateBookmarkMutationVariables = Types.Exact<{
  input: Types.CreateBookmarkInput;
}>;

export type CreateBookmarkMutation = {
  __typename?: 'Mutation';
  createBookmark: {
    __typename?: 'Bookmark';
    id: string;
    bookmarkId: string;
    type?: Types.BookmarkType | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    account: { __typename?: 'Account'; address: string; id: number; name: string };
  };
};

export type RemoveBookmarkMutationVariables = Types.Exact<{
  input: Types.RemoveBookmarkInput;
}>;

export type RemoveBookmarkMutation = {
  __typename?: 'Mutation';
  removeBookmark: {
    __typename?: 'Bookmark';
    id: string;
    bookmarkId: string;
    type?: Types.BookmarkType | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    account: { __typename?: 'Account'; address: string; id: number; name: string };
  };
};

export const BookmarkFieldsFragmentDoc = `
    fragment BookmarkFields on Bookmark {
  id
  account {
    address
    id
    name
  }
  bookmarkId
  type
  createdAt
  updatedAt
}
    `;
export const BookmarkDocument = `
    query Bookmark($id: String!) {
  bookmark(id: $id) {
    ...BookmarkFields
  }
}
    ${BookmarkFieldsFragmentDoc}`;
export const BookmarkByAccountIdDocument = `
    query BookmarkByAccountId($after: String, $before: String, $first: Int = 20, $last: Int, $accountId: Int!, $bookmarkType: BookmarkType!, $orderBy: BookmarkOrder, $skip: Int) {
  allBookmarkByAccountId(
    after: $after
    before: $before
    first: $first
    last: $last
    orderBy: $orderBy
    skip: $skip
    accountId: $accountId
    bookmarkType: $bookmarkType
  ) {
    totalCount
    edges {
      cursor
      node {
        ...BookmarkFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${BookmarkFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const CheckIfHasBookmarkedDocument = `
    query CheckIfHasBookmarked($bookmarkId: String!, $bookmarkType: BookmarkType!) {
  checkIfHasBookmarked(bookmarkId: $bookmarkId, bookmarkType: $bookmarkType)
}
    `;
export const CreateBookmarkDocument = `
    mutation CreateBookmark($input: CreateBookmarkInput!) {
  createBookmark(data: $input) {
    ...BookmarkFields
  }
}
    ${BookmarkFieldsFragmentDoc}`;
export const RemoveBookmarkDocument = `
    mutation RemoveBookmark($input: RemoveBookmarkInput!) {
  removeBookmark(data: $input) {
    ...BookmarkFields
  }
}
    ${BookmarkFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  endpoints: build => ({
    Bookmark: build.query<BookmarkQuery, BookmarkQueryVariables>({
      query: variables => ({ document: BookmarkDocument, variables })
    }),
    BookmarkByAccountId: build.query<BookmarkByAccountIdQuery, BookmarkByAccountIdQueryVariables>({
      query: variables => ({ document: BookmarkByAccountIdDocument, variables })
    }),
    CheckIfHasBookmarked: build.query<CheckIfHasBookmarkedQuery, CheckIfHasBookmarkedQueryVariables>({
      query: variables => ({ document: CheckIfHasBookmarkedDocument, variables })
    }),
    CreateBookmark: build.mutation<CreateBookmarkMutation, CreateBookmarkMutationVariables>({
      query: variables => ({ document: CreateBookmarkDocument, variables })
    }),
    RemoveBookmark: build.mutation<RemoveBookmarkMutation, RemoveBookmarkMutationVariables>({
      query: variables => ({ document: RemoveBookmarkDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const {
  useBookmarkQuery,
  useLazyBookmarkQuery,
  useBookmarkByAccountIdQuery,
  useLazyBookmarkByAccountIdQuery,
  useCheckIfHasBookmarkedQuery,
  useLazyCheckIfHasBookmarkedQuery,
  useCreateBookmarkMutation,
  useRemoveBookmarkMutation
} = injectedRtkApi;
