/* eslint-disable */ /**
  *
  * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
  *
  * instead, edit one of the `.graphql` files in this project and run
  *
  * yarn graphql-codegen
  *
  * for this file to be re-created
  */

import * as Types from '../../generated/types.generated';

import { BasicPageInfoFieldsFragmentDoc } from '../../graphql/fragments/basic-page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type AccountQueryVariables = Types.Exact<{
  id: Types.Scalars['Int']['input'];
}>;


export type AccountQuery = { __typename?: 'Query', account: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } };

export type GetAccountByAddressQueryVariables = Types.Exact<{
  address: Types.Scalars['String']['input'];
}>;


export type GetAccountByAddressQuery = { __typename?: 'Query', getAccountByAddress: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } };

export type AllFollowersByPageQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  id: Types.Scalars['String']['input'];
}>;


export type AllFollowersByPageQuery = { __typename?: 'Query', allFollowersByPage: { __typename?: 'AccountBasicConnection', totalCount: number, edges: Array<{ __typename?: 'AccountBasicEdge', cursor: string, node: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } }>, pageInfo: { __typename?: 'BasicPageInfo', endCursor: string, hasNextPage: boolean } } };

export type AllFollowersByTokenQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  id: Types.Scalars['String']['input'];
}>;


export type AllFollowersByTokenQuery = { __typename?: 'Query', allFollowersByToken: { __typename?: 'AccountBasicConnection', totalCount: number, edges: Array<{ __typename?: 'AccountBasicEdge', cursor: string, node: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } }>, pageInfo: { __typename?: 'BasicPageInfo', endCursor: string, hasNextPage: boolean } } };

export type AccountFieldsFragment = { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null };

export type CreateAccountMutationVariables = Types.Exact<{
  input: Types.CreateAccountInput;
}>;


export type CreateAccountMutation = { __typename?: 'Mutation', createAccount: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } };

export type ImportAccountMutationVariables = Types.Exact<{
  input: Types.ImportAccountInput;
}>;


export type ImportAccountMutation = { __typename?: 'Mutation', importAccount: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } };

export type UpdateAccountMutationVariables = Types.Exact<{
  input: Types.UpdateAccountInput;
}>;


export type UpdateAccountMutation = { __typename?: 'Mutation', updateAccount: { __typename?: 'Account', id: number, name: string, address: string, hash160?: string | null, mnemonicHash?: string | null, encryptedMnemonic?: string | null, encryptedSecret?: string | null, publicKey?: string | null, language: string, followersCount?: number | null, followingsCount?: number | null, followingPagesCount?: number | null, totalDanaViewScore?: number | null, website?: string | null, description?: string | null, createCommentFee?: string | null, createdAt: any, updatedAt: any, avatar?: string | null, cover?: string | null, pages?: Array<{ __typename?: 'Page', id: string, name: string }> | null, accountDana?: { __typename?: 'AccountDana', danaGiven?: number | null, danaReceived?: number | null, danaBurnUp: number, danaBurnDown: number, danaBurnScore: number, danaReceivedUp: number, danaReceivedDown: number, danaReceivedScore: number } | null } };

export const AccountFieldsFragmentDoc = `
    fragment AccountFields on Account {
  id
  name
  address
  hash160
  mnemonicHash
  encryptedMnemonic
  encryptedSecret
  publicKey
  language
  pages {
    id
    name
  }
  followersCount
  followingsCount
  followingPagesCount
  totalDanaViewScore
  website
  description
  createCommentFee
  createdAt
  updatedAt
  avatar
  cover
  accountDana {
    danaGiven
    danaReceived
    danaBurnUp
    danaBurnDown
    danaBurnScore
    danaReceivedUp
    danaReceivedDown
    danaReceivedScore
  }
}
    `;
export const AccountDocument = `
    query Account($id: Int!) {
  account(id: $id) {
    ...AccountFields
  }
}
    ${AccountFieldsFragmentDoc}`;
export const GetAccountByAddressDocument = `
    query getAccountByAddress($address: String!) {
  getAccountByAddress(address: $address) {
    ...AccountFields
  }
}
    ${AccountFieldsFragmentDoc}`;
export const AllFollowersByPageDocument = `
    query AllFollowersByPage($after: String, $first: Int = 20, $id: String!) {
  allFollowersByPage(after: $after, first: $first, id: $id) {
    totalCount
    edges {
      cursor
      node {
        ...AccountFields
      }
    }
    pageInfo {
      ...BasicPageInfoFields
    }
  }
}
    ${AccountFieldsFragmentDoc}
${BasicPageInfoFieldsFragmentDoc}`;
export const AllFollowersByTokenDocument = `
    query AllFollowersByToken($after: String, $first: Int = 20, $id: String!) {
  allFollowersByToken(after: $after, first: $first, id: $id) {
    totalCount
    edges {
      cursor
      node {
        ...AccountFields
      }
    }
    pageInfo {
      ...BasicPageInfoFields
    }
  }
}
    ${AccountFieldsFragmentDoc}
${BasicPageInfoFieldsFragmentDoc}`;
export const CreateAccountDocument = `
    mutation createAccount($input: CreateAccountInput!) {
  createAccount(data: $input) {
    ...AccountFields
  }
}
    ${AccountFieldsFragmentDoc}`;
export const ImportAccountDocument = `
    mutation importAccount($input: ImportAccountInput!) {
  importAccount(data: $input) {
    ...AccountFields
  }
}
    ${AccountFieldsFragmentDoc}`;
export const UpdateAccountDocument = `
    mutation updateAccount($input: UpdateAccountInput!) {
  updateAccount(data: $input) {
    ...AccountFields
  }
}
    ${AccountFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: (build) => ({
    Account: build.query<AccountQuery, AccountQueryVariables>({
      query: (variables) => ({ document: AccountDocument, variables })
    }),
    getAccountByAddress: build.query<GetAccountByAddressQuery, GetAccountByAddressQueryVariables>({
      query: (variables) => ({ document: GetAccountByAddressDocument, variables })
    }),
    AllFollowersByPage: build.query<AllFollowersByPageQuery, AllFollowersByPageQueryVariables>({
      query: (variables) => ({ document: AllFollowersByPageDocument, variables })
    }),
    AllFollowersByToken: build.query<AllFollowersByTokenQuery, AllFollowersByTokenQueryVariables>({
      query: (variables) => ({ document: AllFollowersByTokenDocument, variables })
    }),
    createAccount: build.mutation<CreateAccountMutation, CreateAccountMutationVariables>({
      query: (variables) => ({ document: CreateAccountDocument, variables })
    }),
    importAccount: build.mutation<ImportAccountMutation, ImportAccountMutationVariables>({
      query: (variables) => ({ document: ImportAccountDocument, variables })
    }),
    updateAccount: build.mutation<UpdateAccountMutation, UpdateAccountMutationVariables>({
      query: (variables) => ({ document: UpdateAccountDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };


