/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { api } from '@store/baseApi';
export type AllCoinListQueryVariables = Types.Exact<{ [key: string]: never }>;

export type AllCoinListQuery = {
  __typename?: 'Query';
  allCoinList: Array<{ __typename?: 'CoinList'; id: number; name: string; alias: string }>;
};

export const AllCoinListDocument = `
    query AllCoinList {
  allCoinList {
    id
    name
    alias
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    AllCoinList: build.query<AllCoinListQuery, AllCoinListQueryVariables | void>({
      query: variables => ({ document: AllCoinListDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
