/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import { api } from '@store/baseApi';
export type AllCurrenciesQueryVariables = Types.Exact<{ [key: string]: never }>;

export type AllCurrenciesQuery = {
  __typename?: 'Query';
  allCurrencies: Array<{ __typename?: 'Currencies'; id: number; code: string; name: string }>;
};

export const AllCurrenciesDocument = `
    query AllCurrencies {
  allCurrencies {
    id
    code
    name
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    AllCurrencies: build.query<AllCurrenciesQuery, AllCurrenciesQueryVariables | void>({
      query: variables => ({ document: AllCurrenciesDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
