  /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * yarn graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../generated/types.generated';

import {
  PageInfoFieldsFragmentDoc,
  PostMeiliPageInfoFieldsFragmentDoc
} from '../../graphql/fragments/page-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type ProductQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;

export type ProductQuery = {
  __typename?: 'Query';
  product: {
    __typename?: 'Product';
    id: string;
    name: string;
    price: number;
    priceUnit: string;
    phoneNumber: string;
    title: string;
    categoryId?: string | null;
    description: string;
    imageUploadableId: string;
    createdAt: any;
    updatedAt: any;
    page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
  };
};

export type ProductsQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  orderBy?: Types.InputMaybe<Types.ProductOrder>;
  query?: Types.InputMaybe<Types.Scalars['String']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type ProductsQuery = {
  __typename?: 'Query';
  allProducts: {
    __typename?: 'ProductConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'ProductEdge';
      cursor: string;
      node: {
        __typename?: 'Product';
        id: string;
        name: string;
        price: number;
        priceUnit: string;
        phoneNumber: string;
        title: string;
        categoryId?: string | null;
        description: string;
        imageUploadableId: string;
        createdAt: any;
        updatedAt: any;
        page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type ProductsByPageIdQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  orderBy?: Types.InputMaybe<Types.ProductOrder>;
  id?: Types.InputMaybe<Types.Scalars['String']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
  minBurnFilter?: Types.InputMaybe<Types.Scalars['Int']>;
}>;

export type ProductsByPageIdQuery = {
  __typename?: 'Query';
  allProductsByPageId: {
    __typename?: 'ProductConnection';
    totalCount?: number | null;
    edges?: Array<{
      __typename?: 'ProductEdge';
      cursor: string;
      node: {
        __typename?: 'Product';
        id: string;
        name: string;
        price: number;
        priceUnit: string;
        phoneNumber: string;
        title: string;
        categoryId?: string | null;
        description: string;
        imageUploadableId: string;
        createdAt: any;
        updatedAt: any;
        page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
      };
    }> | null;
    pageInfo: {
      __typename?: 'PageInfo';
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
};

export type ProductFieldsFragment = {
  __typename?: 'Product';
  id: string;
  name: string;
  price: number;
  priceUnit: string;
  phoneNumber: string;
  title: string;
  categoryId?: string | null;
  description: string;
  imageUploadableId: string;
  createdAt: any;
  updatedAt: any;
  page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
};

export type CreateProductMutationVariables = Types.Exact<{
  input: Types.CreateProductInput;
}>;

export type CreateProductMutation = {
  __typename?: 'Mutation';
  createProduct: {
    __typename?: 'Product';
    id: string;
    name: string;
    price: number;
    priceUnit: string;
    phoneNumber: string;
    title: string;
    categoryId?: string | null;
    description: string;
    imageUploadableId: string;
    createdAt: any;
    updatedAt: any;
    page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
  };
};

export type DeleteProductMutationVariables = Types.Exact<{
  input: Types.DeleteProductInput;
}>;

export type DeleteProductMutation = {
  __typename?: 'Mutation';
  deleteProduct: {
    __typename?: 'Product';
    id: string;
    name: string;
    price: number;
    priceUnit: string;
    phoneNumber: string;
    title: string;
    categoryId?: string | null;
    description: string;
    imageUploadableId: string;
    createdAt: any;
    updatedAt: any;
    page: { __typename?: 'Page'; id: string; name: string; pageAccountId: number };
  };
};

export const ProductFieldsFragmentDoc = `
    fragment ProductFields on Product {
  id
  page {
    id
    name
    pageAccountId
  }
  name
  price
  priceUnit
  phoneNumber
  title
  categoryId
  description
  imageUploadableId
  createdAt
  updatedAt
}
    `;
export const ProductDocument = `
    query Product($id: String!) {
  product(id: $id) {
    ...ProductFields
  }
}
    ${ProductFieldsFragmentDoc}`;
export const ProductsDocument = `
    query Products($after: String, $before: String, $first: Int = 20, $last: Int, $orderBy: ProductOrder, $query: String, $skip: Int) {
  allProducts(
    after: $after
    before: $before
    first: $first
    last: $last
    orderBy: $orderBy
    query: $query
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...ProductFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${ProductFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const ProductsByPageIdDocument = `
    query ProductsByPageId($after: String, $before: String, $first: Int = 20, $last: Int, $orderBy: ProductOrder, $id: String, $skip: Int, $minBurnFilter: Int) {
  allProductsByPageId(
    after: $after
    before: $before
    first: $first
    last: $last
    orderBy: $orderBy
    id: $id
    skip: $skip
    minBurnFilter: $minBurnFilter
  ) {
    totalCount
    edges {
      cursor
      node {
        ...ProductFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
    ${ProductFieldsFragmentDoc}
${PageInfoFieldsFragmentDoc}`;
export const CreateProductDocument = `
    mutation createProduct($input: CreateProductInput!) {
  createProduct(data: $input) {
    ...ProductFields
  }
}
    ${ProductFieldsFragmentDoc}`;
export const DeleteProductDocument = `
    mutation deleteProduct($input: DeleteProductInput!) {
  deleteProduct(data: $input) {
    ...ProductFields
  }
}
    ${ProductFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  overrideExisting: true,
  endpoints: build => ({
    Product: build.query<ProductQuery, ProductQueryVariables>({
      query: variables => ({ document: ProductDocument, variables })
    }),
    Products: build.query<ProductsQuery, ProductsQueryVariables | void>({
      query: variables => ({ document: ProductsDocument, variables })
    }),
    ProductsByPageId: build.query<ProductsByPageIdQuery, ProductsByPageIdQueryVariables | void>({
      query: variables => ({ document: ProductsByPageIdDocument, variables })
    }),
    createProduct: build.mutation<CreateProductMutation, CreateProductMutationVariables>({
      query: variables => ({ document: CreateProductDocument, variables })
    }),
    deleteProduct: build.mutation<DeleteProductMutation, DeleteProductMutationVariables>({
      query: variables => ({ document: DeleteProductDocument, variables })
    })
  })
});

export { injectedRtkApi as api };
export const {
  useProductQuery,
  useLazyProductQuery,
  useProductsQuery,
  useLazyProductsQuery,
  useProductsByPageIdQuery,
  useLazyProductsByPageIdQuery,
  useCreateProductMutation,
  useDeleteProductMutation
} = injectedRtkApi;
