-- AlterTable
ALTER TABLE "account_dana" ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "comment_dana" ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "hashtag_dana" ADD COLUMN     "dana_received_down" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_up" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "page_dana" ADD COLUMN     "dana_received_down" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_up" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "post_dana" ADD COLUMN     "dana_received_down" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_up" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "token_dana" ADD COLUMN     "dana_received_down" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received_up" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 0;
